---
title: "#CPMK1 - 19523118 - 19523201 - 19523199k"
output: html_notebook
---
#1. Matrix
```{r}
#a) 
A <- matrix( c( 1,2,3,4,5,6,7,8,9), 3, 3, TRUE)
colnames(A) <- c('col1','col2','col3')
rownames(A) <- c('row1','row2','row3')
A

#b)
diag(A)

#c)
det(A)

#d)
Solve(A)

#e)
t(A) %*% A

#f)
eigen(A)
```


#2. Matrix
```{r}
B <- matrix( c(1,1,3, 5,2,6, -2,-1,-3), 3, 3, TRUE)
B

#a 
B <- B%*%B%*%B
B

#b
B <- matrix( c(1,1,2, 5,2,7, -2,-1,-3), 3, 3, TRUE)
B
```


#3. Matrix
```{r}
M <- matrix( c( 1,2,3,8,2,9), 3, 2, TRUE)
M

N <- matrix( c( 5,4,8,2), 2, 2, TRUE)
N

#a)
M %*% N

#b)
M %*% solve(N)

#c)
M %*% t(N)

#d)
3 *( (M %*% solve(N)) +( M %*% t(N) ) )

```


#4. SLE
```{r}
J <- matrix( c(1, -2, 3, 2, 1, 1, -3, 2, -2), 3, 3, TRUE)
J

j <- c(7, 4, -10)
j

# Show the equation
showEqn(J , j ) 

# Find solution
Solve(J , j ) 

# Plot the equation
plotEqn3d(J , j ) 

# Solution used reduced echelon form
echelon(J,j, verbose= TRUE, fractions= TRUE)
```


#5
```{r}
X <- matrix( c( 1,2,3,4,5,6,7,8,9), 3, 3, TRUE)
X

for (r in 1:3 ){
  
  for (c in 1:3 ){
    
    if( r==1 ){
      
      if( c==1 | c==2 | c==3){
        X[r,c]=0
      }
    }
    if ( c==1 ){
      
      if ( r==2 | r==3 ){
        X[r,c]=1
      }
    }
  }
}
```

